server:
  port: 8889
spring:
  application:
    name: config-server-git
  cloud:
    config:
      server:
        git:
          uri: "https://github.com/busecnky/java5cloudconfig.git"
          default-label: main
          skip-ssl-validation: true
          username: busecnky
          password: ${GIT_PASSWORD}

#DİKKAT BURDA PASSWORD ASLA VE ASLA TUTULMAMALIDIR. Bunun yerine env kullanılarak çekilmelidir.
#Diğer türlü bu bilgiyi GIT e pushladığınız zaman ya bu token silinecektir ya da güvenlik açısından askıya alınacaktır.